module.exports = {
    ADMINCOLLECTION: "ADMIN",
    USERCOLLECTION:  "USERS",
    PRODUCTCOLLECTION: "PRODUCT",
    CARTCOLLECTION : 'CART',
    WISHLISTCOLLECTION : "WISHLIST",
    COUPONCOLLECTION : "COUPONS",
    ORDERCOLLECTION : "ORDERS",
    COMMUNITY: "COMMUNITY"
}