module.exports = {
    ADMINCOLLECTION: "ADMIN",
    USERCOLLECTION:  "USER",
    PRODUCTCOLLECTION: "PRODUCT",
    CARTCOLLECTION : 'CART',
    WISHLISTCOLLECTION : "WISHLIST",
    COUPONCOLLECTION : "COUPONS"
}